### ISSUE TITLE
Focused panel size is too narrow when using vertical-tabs

### ISSUE THREAD

**Issue by rnyberg** [timomeh/hey-pane#1]
Editor-area is no longer visible when using https://atom.io/packages/vertical-tabs package. 

I guess the problem can be fixed manually by setting a wider size, once you implement configurations, but I reckon it could be larger to begin with when certain conditions are met (such as having aforementioned package enabled).

**Comment by timomeh** [comment]
Thank you for reporting! I'll publish a new release with configurations in the next minutes.

**Comment by timomeh** [comment]
Fixed with v0.2.0 (2e143f6744abf6b4b97905bccbffe17a558c47c5). 🎉 

I tested the new version with vertical-tabs, seems to work. Please reopen if this still causes some issues.
