### ISSUE TITLE
Suggestion: Some sort of Delay or non-switch for quick copy

### ISSUE THREAD

**Issue by benyanke** [timomeh/hey-pane#13]
I am loving this extension! However, one of the painpoints for me on follow mode is when I need to copy a single value from a small pane for use in a large pane. As I'm preparing to copy, the small pane ends up reflowing and changing the location of the item to copy, then again as I switch back.

Perhaps there could be a programmable delay, or some other UI option or feature to help solve this issue?

**Comment by timomeh** [comment]
That sounds very reasonable. I'll include a configurable delay of the follow mode if I have some time.

**Comment by benyanke** [comment]
http://i.imgur.com/Ndm20.jpg

**Comment by benyanke** [comment]
![Great Success](http://i.imgur.com/Ndm20.jpg "IMG: Great Success")

**Comment by timomeh** [comment]
I just published this feature as version 1.1.0 🎉 

Sorry for taking so long, I was quite busy. You can find the delay in the configurations. 🙂
