### ISSUE TITLE
hey pane error

### ISSUE THREAD

**Issue by savvyalley** [timomeh/hey-pane#14]
everything is reporting an error.  It says 1.15 is out of date and i should upgrade to 1.21, it will not run the upgrade.  and every new entry meets a new error.  Any tips

Ali 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.6
**Thrown From**: [hey-pane](https://github.com/timomeh/hey-pane) package 1.0.0

### Stack Trace

Uncaught TypeError: atom.workspace.getCenter is not a function

```
At /Users/thecorletts/.atom/packages/hey-pane/lib/hey-pane.js:72

TypeError: atom.workspace.getCenter is not a function
    at Object.doFocus (/packages/hey-pane/lib/hey-pane.js:72:37)
    at Object.startFollow (/packages/hey-pane/lib/hey-pane.js:54:10)
    at /packages/hey-pane/lib/hey-pane.js:49:53
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at stoppedChangingActivePaneItemCallback (/app.asar/src/pane-container.js:352:36)
```

### Commands

```
     -4:21.8.0 core:save (input.hidden-input)
     -1:33.1.0 core:move-right (input.hidden-input)
     -1:30.2.0 core:save (input.hidden-input)
  2x -1:04.2.0 core:backspace (input.hidden-input)
     -0:36.5.0 hey-pane:toggle-focus-of-active-pane (input.hidden-input)
```

### Non-Core Packages

```
atom-ftp-editor 0.5.0 
atom-material-ui 1.3.10 
browser-plus 0.0.98 
ftp-remote-edit 0.12.3 
hey-pane 1.0.0 
open-in-browser 0.5.2 
```

**Comment by timomeh** [comment]
Yeah, Atom 1.15 is pretty out of date and not supported by hey-pane. Please update Atom to a newer version in order to use this plugin. If you can't use Atom at all because of the error, start Atom it with `atom --safe`. This won't load any packages or custom configurations.

Please close this issue if you updated Atom and the Error disappeared.

**Comment by timomeh** [comment]
@savvyalley Is the issue solved?

**Comment by timomeh** [comment]
I assume this issue is resolved since there's no answer for 14 days.
