### ISSUE TITLE
Suggestion: Add option to enable follow mode by default

### ISSUE THREAD

**Issue by Jargonius** [timomeh/hey-pane#19]
I find myself having to re-enable follow mode every time I start up atom.  Looking at the code it would be very simple to add a setting to enable it by default and turn on follow mode on start up if that setting is checked.  I have hacked it to work on my machine and I can share how I did it if you would like.

**Comment by timomeh** [comment]
Thanks for your suggestion, I can also see the benefit of this option. If you already implemented it, feel free to open a [Pull Request](https://github.com/timomeh/hey-pane/compare) 🙂  I would highly appreciate it.

If you've never made a Pull Request before, this would be a great way to get some first experience with it! You can read [here] more about how to do a Pull Requests.

**Comment by StefanBrand** [comment]
@Jargonius Could you open that Pull Request, or at least share your code, so that someone else can do it? :)

**Comment by neelusb** [comment]
I've opened a pull request for it here: https://github.com/timomeh/hey-pane/pull/29.

**Comment by timomeh** [comment]
Feature added in v1.2.0. Thank you @neelusb!
