### ISSUE TITLE
cmd + shift + K does NOT zoom settings panel 

### ISSUE THREAD

**Issue by wayneseymour** [timomeh/hey-pane#2]
## Problem 

I think this plugin is nice, but I'd like it to work on the settings panel as well.
I am not against opening a PR but not sure where to start.  I'll go looking into the src if you tell me where to look.  :1st_place_medal: 

## My System
```
$ atom --version
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
> OS: Mac OS X El Capitan

**Comment by timomeh** [comment]
Hi! Thanks for reporting.

Strange. Resizing the Settings Panel works for me with the key-combination and also with the Command Palette Command: `Hey Pane: Toggle Focus Of Active Pane`. I have the same specs, although I'm on version `1.14.2`, but that shouldn't break things. (There's no new update to `1.14.3` for me)

Could you please test, if it works, if the Pane with the Settings is focused and you run `Toggle Focus Of Active Pane` via the Command Palette? If that works, there might be some other key-combination overriding Hey-Pane.

It should work theoretically with every type of pane, no matter if Editor, Settings or some Plugin's Content (if it's inside a pane element). So, it all comes down to the `doFocus()` method inside `lib/hey-pane.js`, respectively these few lines:
https://github.com/timomeh/hey-pane/blob/3d233b57ab2c370bc1f25c057efea5ae5d1eb757/lib/hey-pane.js#L77-L82

If it isn't a problem with the key-combination, I'll document some of the code (should've done this earlier) and dive into this problem.

**Comment by wayneseymour** [comment]
You are going to think I'm nuts, but its not happening any longer.  
Either it's a race, or my eyes were tired earlier, we'll go with *tired eyes*.

Thanks @timomeh  (sorry to interrupt you)

**Comment by timomeh** [comment]
No problem, good to hear that it works! I'm happy to help. 🙂

**Comment by ehellman** [comment]
I'm in the same boat, not working at all for me even if I reassign the keybinding. The menu item doesn't work either. Is there any way to debug this?

**Comment by timomeh** [comment]
@ehellman Sounds like a different issue. Could you please open a new issue with some informations, like Atom Version and maybe installed packages, which could interfere with the Pane?

You can kinda debug it by opening the DevTools (View > Developer > Toggle DevTools) and toggle focus on a pane. It should look like this, with `flex-grow: 0.96` and `hey-pane-focus` class added. The class does nothing (except giving the ability to style the focused/unfocused panes). The `flex-grow` value sets the pane width. If you change this value in DevTools, you should see the pane becoming bigger/smaller. Also, if you resize the pane in the editor, you should see those values change.

<img width="1183" alt="screen shot 2017-02-24 at 10 03 19" src="https://cloud.githubusercontent.com/assets/4227520/23297191/d5ddd714-fa78-11e6-863b-4f43b4b7249d.png">
