### ISSUE TITLE
Bug: Panes change focus when follow mode on and side panels clicked

### ISSUE THREAD

**Issue by Jargonius** [timomeh/hey-pane#20]
Panes change focus when follow mode is on and the side panels such as tree view are clicked.  It's really frustrating to click on a file in the tree to preview it and have the file open in a pane only to then have that pane instantly squished as another pane is focused.  Let me know if I can provide any more detail or if I can help in any other way.

**Comment by timomeh** [comment]
Thanks for submitting this issue, and sorry for not responding so long, I kinda forgot about new issues...

You're right, this is an annoying behavior. I didn't notice it because I'm not really using follow mode.

If you could submit a Pull Request which fixes this, I would be happy to merge it.

**Comment by timomeh** [comment]
Feature added in v1.2.0. Thank you @aviatesk!
