### ISSUE TITLE
Cannot turn off `Follow Of Active Pane` after trigger it under Atom1.17.0-beta3

### ISSUE THREAD

**Issue by ooJerryLeeoo** [timomeh/hey-pane#6]
@timomeh Can you take a look ?

**Comment by timomeh** [comment]
Thanks for reporting. The package seems to be broken under 1.17.0-beta3. I guess it has something to do with the UI changes. I'll investigate it and fix if soon.

**Comment by timomeh** [comment]
I just published [v0.3.0](https://github.com/timomeh/hey-pane/releases/tag/v0.3.0). I've tested it successfully in 1.17.0-beta3. 🚀  Go grab it. If there are still problems, feel free to reopen this issue.

Again, thank you very much for reporting! Without such contributions this error would still exist if Atom 1.17 stable rolls out, thus it would be a big inconvenience for a few thousand people.

**Comment by ooJerryLeeoo** [comment]
@timomeh Thanks!! v0.3.0 work very well for me :+1:

**Comment by ooJerryLeeoo** [comment]
@timomeh, But I got this deprecation:

`atom.workspace.paneContainer` has always been private, but it is now gone. Please use `atom.workspace.getCenter()` instead and consult the workspace API docs for public methods.
```
Workspace.get (<embedded>:24619:18)
resursiveSet (/Users/jerrylee/.atom/packages/hey-pane/lib/hey-pane.js:105:48)
Object.doFocus (/Users/jerrylee/.atom/packages/hey-pane/lib/hey-pane.js:112:5)
Object.toggleFocus (/Users/jerrylee/.atom/packages/hey-pane/lib/hey-pane.js:70:52)
atom-workspace.heyPaneToggleFocusOfActivePane (/Users/jerrylee/.atom/packages/hey-pane/lib/hey-pane.js:37:22)
CommandRegistry.handleCommandEvent (<embedded>:18796:35)
```
