### ISSUE TITLE
Does hey-pane shortcut work on Windows 10?

### ISSUE THREAD

**Issue by Alpha-UMi** [timomeh/hey-pane#9]
After installing this package, I noticed that it don't work on Windows. I mean, Shift-Ctrl-K instead of Shift-Cmd-K that seems a Mac shortcut. I modified the keymap.json file substituting shift-cmd-k with shift-ctrl-k, but ti didn't work. Any advice?

**Comment by timomeh** [comment]
Can you post the snippet from your keymap.json with the new keymapping?

Also, you can check the keybinding by activating Keybinding Resolver (through the command palette) and trying your new shortcut. If should resolve to `hey-pane:toggle-focus-of-active-pane`.

Nonetheless, I should add support for Windows out of the box.

**Comment by Alpha-UMi** [comment]
Of course, here it is:

`{
  "atom-text-editor": {
    "shift-ctrl-k": "hey-pane:toggle-focus-of-active-pane"
  }
}`

>It should be pretty simple to edit, but it's not working on Windows 10. Thank you for your interest in this issue.

**Comment by Alpha-UMi** [comment]
{
  "atom-text-editor": {
    "shift-ctrl-k": "hey-pane:toggle-focus-of-active-pane"
  }
}

This is the content of hey-pane.json file. I've just substituted cmd with ctrl.

**Comment by timomeh** [comment]
Don't modify the hey-pane.json file directly. You can assign your own shortcuts in your keymap.cson/json.

To do this, select "Open your keymap" in the Command Palette. Then a file called keymap.cson or keymap.json should open.

If it's a json, add the code you posted.  
If it's a cson, add this:

```cson
'atom-text-editor':
  'shift-ctrl-k': 'hey-pane:toggle-focus-of-active-pane'
```

The keymap file should include a big comment block on how to edit this file properly.

To debug the shortcut, you can toggle the Key Binding Resolver (in the command palette) and press the shortcut. You should see a window telling you which command the shortcut is assigned to. If you press <kbd>shift-ctrl-k</kbd>, you should see that the hey-pane command get's triggered, if the key binding resolves correctly.

**Comment by Alpha-UMi** [comment]
Hi timomeh!

Thank you for pointing me out in the right direction. I was focusing on the wrong file (I know, I'm a noob, just started learning Atom).

Curiously, I've found that Atom x64 for Windows 10 (which at least it's the one I'm using), won't accept keybinds like Shift-Ctrl-K, Shift-Ctrl-I or Shift-Ctrl-L... strange! In the Key Binding Resolver they aren't even tiped... I mean, if I press Shift-Ctrl-K, the Resolver only shows Shift-Ctrl and it seems the "K" is broken, although if I press "K" alone, of course the output is "K". Strange.

Anyway, following your directions I bound Hey Pane to Shift-Ctrl-J, which works flawlessly. Thank you for support! 👍

**Comment by timomeh** [comment]
No problem, I'm here to help 🙂

I'm going to add a keyboard shortcut for windows out-of-the-box when I have some time, so it's very good to know that shift-ctrl-k doesn't work on Windows. Seems like some sort of reserved shortcut on Windows. Thank you for pointing that out!

**Comment by jest** [comment]
@Alpha-UMi `Cmd` is indeed Mac-specific, however on my Linux it translates to the Windows key (called `Super` down here in Linuxland) and the shortcut Shift-Win-K works fine.
